### ISSUE TITLE
KickFFT not working?

### ISSUE THREAD

**Issue by chris-wiz** [LinnesLab/KickFFT#3]
Hello all,

Thank you for sharing this piece of code. Unfortunately the bare example did not work for me. All it outputted for the magnitude was a bunch of zeros. Is it possible, that you forgot to upload the KickFFT.c file?

Infos:
I am using Arduino IDE 2.1.0 on Windows, I installed this library via the buildin library manager. I am using an Arduino nano.

**Comment by hoilett** [comment]
Hi, Chris. The Arduino Nano doesn't have enough RAM to run this library. I should probably change the architecture to SAM boards. I apologize for that. Do you have another Arduino to test it with?

**Comment by chris-wiz** [comment]
Hi hoilett,
Ah, I see the problem, too less RAM. 
I dont have a different Arduino at hand, but thank you very much for your fast response.

**Comment by hoilett** [comment]
No problem. Getting it to work on an Uno with only 2k RAM is tough, but I should update the documentation so people know the limitations.
